baseURL = "https://xinbinh.com"
title = "Xinbin Huang"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minimo"

disqusShortname = ""
googleAnalytics = ""

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown", "_files$", "_cache$"]

[params.info]
description = "Data Scientist interestd in NLP, Deep Learning, and Distributed computing"
title404 = "Nothing's here!"

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Xinbin Huang"
startYear = "2018"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
archiveDateFormat = "Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
hideSocialMenu = true
showReadingTime = true
taxonomyCloudShuffle = true

[params.sidebar]
enable = true
sticky = true

[params.widgets]
homepage = ["recent_posts" ]
sidebar = ["about","social_menu"]

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
email = "xbhuang93@hotmail.com"
github = "xinbinhuang"
linkedin = "xinbin-huang"
twitter = "xinbinh"


[params.social.config]
platforms = ["github","facebook","twitter","instagram","email","codepen","gitlab","linkedin","telegram","google_scholar"]

[taxonomies]
author = "authors"
category = "categories"
tag = "tags"

[permalinks]
page = "/:slug/"

[[menu.main]]
name = "Bin"
weight = 5
identifier = "home"
url = "/"


[[menu.main]]
name = "About me"
weight = 10
identifier = "about"
url = "/about/"

[[menu.main]]
name = "posts"
weight = 20
identifier = "posts"
url = "/posts/"

[[menu.main]]
name = "projects"
weight = 30
identifier = "projects"
url = "/projects/"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.en]
lang = "en"
languageName = "English"
weight = 1
